routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  if(\Auth::check()){
    return redirect()->to('/home');
  }
  return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('businesses', 'BusinessesController');
Route::resource('venues', 'VenuesController');
Route::resource('cities', 'CitiesController');
Route::get('venues/{id}/timings', array('uses'=>'VenuesController@getTimings', 'as'=>'venues.timings.get'));
Route::post('venues/{id}/timings', array('uses'=>'VenuesController@postTimings', 'as'=>'venues.timings.post'));

Route::get('venues/{id}/delivery_locations', array('uses'=>'VenuesController@getDeliveryLocations', 'as'=>'venues.delivery_locations.get'));
Route::post('venues/{id}/delivery_locations', array('uses'=>'VenuesController@postDeliveryLocations', 'as'=>'venues.delivery_locations.post'));

app/Zone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Zone extends Model
{
    //
  public function city(){
    return $this->belongsTo('\App\City');
  }
}

resources/views/zones/create.blade.php
@extends('layouts.application')
@section('content')
            <div class="card">

                <div class="card-body">

<h1>Create Business Entitie</h1>
<hr/>

{{ Form::open(array('route' => 'businesses.store', 'files'=>true, 'class' => ' ')) }}

  <div class="form-group row">
    {{ Form::label('name', 'Name:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('name', Input::old('name'), array('class'=>'form-control', 'placeholder'=>'Name')) }}
    </div>
  </div>
  <div class="form-group row">
    {{ Form::label('type', 'Type:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
    {{ Form::select('type',  ['cafe'=>'Cafe', 'restaurant'=>'Restaurant'],   Input::old('type'),array('class'=>'form-control', 'placeholder'=>'Select Business Type')) }}
    </div>
  </div>
  <div class="form-group row">
    {{ Form::label('desc', 'Description:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('desc', Input::old('desc'), array('class'=>'form-control', 'placeholder'=>'Description')) }}
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Create', array('class' => 'btn btn-lg btn-primary')) }}
    </div>
  </div>

{{ Form::close() }}
</div>
</div>
@stop

resources/views/zones/edit.blade.php
@extends('layouts.application')
@section('content')
<div class="card">
  <div class="card-body">
    <h1>Edit {{ $business->name }}</h1>

    {{ Form::model($business, array('class' => 'form-horizontal', 'files'=>true, 'method' => 'PATCH', 'route' => array('businesses.update', $business->id))) }}

      <div class="form-group row">
        {{ Form::label('name', 'Name:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::text('name', Input::old('name'), array('class'=>'form-control', 'placeholder'=>'Name')) }}
        </div>
      </div>
      <div class="form-group row">
        {{ Form::label('type', 'Type:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
        {{ Form::select('type',  ['cafe'=>'Cafe', 'restaurant'=>'Restaurant'],   Input::old('type'),array('class'=>'form-control', 'placeholder'=>'Select Business Type')) }}
        </div>
      </div>
      <div class="form-group row">
        {{ Form::label('desc', 'Description:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::text('desc', Input::old('desc'), array('class'=>'form-control', 'placeholder'=>'Description')) }}
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-10">
          {{ Form::submit('Edit', array('class' => 'btn btn-lg btn-primary')) }}
        </div>
      </div>

    {{ Form::close() }}
  </div>
</div>
@stop

resources/views/zones/index.blade.php
@extends('layouts.application')
@section('content')
<div class="card">
  <div class="card-body">

    <h1>Business Entities</h1>

    <p>{{ link_to_route('businesses.create', 'Add New Business Entity', null, array('class' => 'btn btn-lg btn-success')) }}</p>

    @if ($businesses->count())
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Venues</th>
            <th>&nbsp;</th>
          </tr>
        </thead>

        <tbody>
          @foreach ($businesses as $business)
            <tr>
              <td>{{{ $business->name }}}</td>
              <td>{{{ $business->type }}}</td>
              <td>{{{ $business->venues->count() }}} venues</td>
              <td>
                {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('businesses.destroy', $business->id))) }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
                {{ link_to_route('businesses.edit', 'Edit', array($business->id), array('class' => 'btn btn-info')) }}
                {{ link_to_route('businesses.show', 'Show', array($business->id), array('class' => 'btn btn-info')) }}
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>

      <div class="row">
        <div class="col-md-12">
          {{ $businesses->render() }}
          <div class="pull-right">
            {{ count($businesses) }} / {{ $businesses->total() }} entries
          </div>
        </div>
      </div>

    @else
      There are no business entities
    @endif
  </div>
</div>
@stop

resources/views/zones/show.blade.php
@extends('layouts.application')
@section('content')
<div class="card">
  <div class="card-body">
    <h1>{{ $business->name }}</h1>
    <hr/>
    <p><b>{{ $business->type }}</b></p>
    {{ $business->desc }}
    @if(count($business->venues)>0)
    <div class="card">
      <div class="card-header">
        Venues
        <a href="{{ route('venues.create', array('bid'=>$business->id)) }}" class="pull-right">Add Venue</a>
      </div>
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>address</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @foreach($business->venues as $venue)
              <tr>
                <th>{{ $venue->id }}</th>
                <th>{{ $venue->name }}</th>
                <th>{{ $venue->getFormattedAddress() }}</th>
                <th>
                  @if($venue->hasDelivery())
                    <span class="label label-success">DELIVERY</span>
                  @else
                    <span class="label label-danger">NO DELIVERY</span>
                  @endif
                </th>
                <th>
                  <a href="{{ route('venues.edit', $venue) }}">Edit</a>
                  <a href="{{ route('venues.show', $venue) }}">Show</a>
                </th>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
    @else
      <div class="alert alert-warning">
        <a href="{{ route('venues.create', array('bid'=>$business->id)) }}" class="pull-right">Add Venue</a>
      </div>
    @endif

    {{ link_to_route('businesses.edit', 'Edit', $business->id, array('class' => 'btn btn-lg btn-default')) }}
    {{ link_to_route('businesses.index', 'Return', $business->id, array('class' => 'btn btn-lg btn-default')) }}
  </div>
</div>
@stop